### ISSUE TITLE
RNBluetoothClassic object is null

### ISSUE THREAD

**Issue by DamianoBarone** [amitferman/with-rn-bluetooth-classic#3]
Mobile Device Environment
Android tablet galaxy s7+

Application Environment
Provide information about your development environment:

React Native version: [e.g. v5.0.1]
RN Bluetooth Classic version: [latest, download today]
Expo (latest)
npm 8.5.0
running on MacBook Pro 11.62
Describe the bug
I can't use any method of RNBluetoothClassic, it give me an error that the object is null
Error: [TypeError: null is not an object (evaluating 'this._nativeModule.isBluetoothEnabled')]
I have imported
import RNBluetoothClassic from 'react-native-bluetooth-classic';
async function btList() {
try {
let devices = await RNBluetoothClassic.isBluetoothEnabled();
} catch (err) {
console.log('Error:', err);
}
}
btList is called in the useEffect() (I'm using function component)
I've installed the react-native-bluetooth-classic with npm and yarn, I have also tried the expo plugin. But same error.
In the main application.jave
@OverRide
protected List getPackages() {
@SuppressWarnings("UnnecessaryLocalVariable")
List packages = new PackageList(this).getPackages();
// Packages that cannot be autolinked yet can be added manually here, for example:
// packages.add(new MyReactNativePackage());
packages.add(new MainReactPackage());
packages.add(new ReactToolbarPackage());
packages.add(new RNBluetoothClassicPackage());
return packages;
}
I added this, I tried different setting, but same problem.

To Reproduce
Steps to reproduce the behaviour:
If I follow step by step your guide I'm ending in this problem

Expected behaviour
I should be able to call all the methods of RNBluetoothClassic
Screenshots

Additional context
your job is incredible, I'm sad that I have to annoying you.
I have also create this post
https://stackoverflow.com/questions/71104150/null-is-not-an-object-evaluating-this-nativemodule-isbluetoothenabled-in-re

**Comment by amitferman** [comment]
Thank you for the details. Could you also include your app.json file?
