### ISSUE TITLE
Still getting error "null is not an object (evaluating 'this._nativeModule.isBluetoothEnabled')"

### ISSUE THREAD

**Issue by ArhumJain** [amitferman/with-rn-bluetooth-classic#4]
I tried installing this expo config plugin but I still get the error stated in the title. Followed all the steps in the README as well as the issues you opened on the main react-native-bluetooth-classic repo. Any ideas what the problem could be? I am testing on a physical Android device.

Code: 
```
const enabled: any = async () => {
  try {
    let enab = await RNBluetoothClassic.isBluetoothEnabled();
    console.log(enab);
  } catch (err) {
    console.log(err);
  }
}
```

app.json:
```
{
  "expo": {
    "name": "MobileTest",
    "slug": "MobileTest",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      "with-rn-bluetooth-classic"
    ]
  }
}

```
Here is the output from `expo config --type introspect`:
https://pastebin.com/Yy5VAyU8

**Comment by amitferman** [comment]
The issue might be caused by different Android API levels requiring different permissions (https://developer.android.com/guide/topics/connectivity/bluetooth/permissions). The plugin currently satisfies permission requirements for Android 11 and below. It looks like newer API levels will also require the `android.permission.BLUETOOTH_SCAN` to look for Bluetooth devices. Can you please try replacing `plugin/src/index.ts` with the following code block? It includes some additional permissions that might fix the issue.

Let me know how it goes,
Amit

```
import { ConfigPlugin, withInfoPlist, AndroidConfig } from "@expo/config-plugins"

// Default usage descriptions
const PROTOCOLS = ['com.apple.m1']
const PERIPHERAL_SHARE = 'Allow $(PRODUCT_NAME) to check bluetooth peripheral info'
const ALWAYS_SHARE = 'Allow $(PRODUCT_NAME) to always use bluetooth info'

// Plugin Props interface
interface PluginProps {
    peripheralUsageDescription?: string;
    alwaysUsageDescription?: string;
    protocols?: string
}

// iOS modifier sets
//  > NSBluetoothPeripheralUsageDescription
//  > NSBluetoothAlwaysUsageDescription
//  > UISupportedExternalAccessoryProtocols
const withIosBLC : ConfigPlugin<PluginProps> = (config, { peripheralUsageDescription, alwaysUsageDescription, protocols} = {}) => 
{
    config = withInfoPlist(config, (config) => {
        // config = {modResults, modRequests, ...}
        config.modResults.NSBluetoothPeripheralUsageDescription =
            peripheralUsageDescription ? 
            peripheralUsageDescription : 
            PERIPHERAL_SHARE
        config.modResults.NSBluetoothAlwaysUsageDescription =
            alwaysUsageDescription ? 
            alwaysUsageDescription : 
            ALWAYS_SHARE
        config.modResults.UISupportedExternalAccessoryProtocols = 
            protocols ?
            protocols :
            PROTOCOLS
        return config
    })
    return config
}

// Android modifier sets permissions
//  > BLUETOOTH
//  > BLUETOOTH_ADMIN
//  > ACCESS_FINE_LOCATION
//  > BLUETOOTH_SCAN (Android 12)
//  > BLUETOOTH_ADVERTISE (Android 12)
//  > BLUETOOTH_CONNECT (Android 12)
const withAndroidBLC : ConfigPlugin<any> = (config, options = {}) => {
    config = AndroidConfig.Permissions.withPermissions(config, [
        'android.permission.BLUETOOTH',
        'android.permission.BLUETOOTH_ADMIN',
        'android.permission.ACCESS_FINE_LOCATION',
        'android.permission.BLUETOOTH_SCAN',
        'android.permission.BLUETOOTH_ADVERTISE',
        'android.permission.BLUETOOTH_CONNECT'
      ]);
    return config
}

// iOS + Android modifier
const withBLC : ConfigPlugin<PluginProps> = (config, { peripheralUsageDescription, alwaysUsageDescription, protocols} = {},) => 
{
    config = withIosBLC(config, {peripheralUsageDescription, alwaysUsageDescription, protocols})
    config = withAndroidBLC(config, {})
    return config
}

module.exports = withBLC
```

**Comment by ArhumJain** [comment]
Thank you for responding Amit. I tried editing the plugin as you advised, but I still get the same error. I did some research and I am debating if I should just write a native module myself for bluetooth. However, Expo GO does not support writing your own native modules but I am curious how you, @kenjdavidson, and many others were able to create react native libraries that bridge native code and can be used with Expo without ejecting it.

**Comment by kenjdavidson** [comment]
The missing permission should only affect the start scan request, I got an open issue about it. The rest of the library is loaded. You're getting a null on the _native module, are you including my library as well as this in package?  Are you getting any other console errors during startup that are hidden? It looks as if the native module isn't available (null) and maybe not even loaded? 

I don't ever use expo, since I was tagged. But I trust it works as many do use it with this library.

**Comment by amitferman** [comment]
@ArhumJain The standard Expo Go runtime you can download from your Android phone does not contain the native files in react-native-bluetooth-classic. Without ejecting Expo and only using the standard runtime, the native code will never be compiled. This is probably why the native module isn't available, as @kenjdavidson mentioned. To resolve this without ejecting, I used [Expo EAS](https://docs.expo.dev/eas/) to [build a runtime environment](https://docs.expo.dev/build/setup/) (similar to the Expo Go app, but with new native dependencies). If you haven't ejected and are not using this, then the native modules will not be available on your Expo Go app, so it won't work.

**Comment by ArhumJain** [comment]
Thank you for the clarification, that clears up why the library was not working for me!
