### ISSUE TITLE
PluginError: Failed to resolve plugin

### ISSUE THREAD

**Issue by Magnetka-dev** [amitferman/with-rn-bluetooth-classic#6]
Hi,
I am building an android app which uses bluetooth and I cant figure out how to build app using this plugin. I am using EAS builds and getting following error: 
`PluginError: Failed to resolve plugin for module 
    "with-rn-bluetooth-classic" relative to 
    "/builds/3yoFW7dC/0/<name>/<project_name>"
    Code: PLUGIN_NOT_FOUND`
I simply installed `react-native-bluetooth-classic` and `with-rn-bluetooth-classic` and added this plugin into plugins in `app.json`.
What am I missing? Thanks!

**Comment by amitferman** [comment]
Hello @Kyiomi,

I haven't worked on this for a while but your setup process sounds right. It looks like it can't resolve the plugin in 'app.json'. Did you confirm whether the plugin exists under the directory in which it's searching? I think it should be in node_modules.

**Comment by Magnetka-dev** [comment]
> Hello @Kyiomi,
> 
> I haven't worked on this for a while but your setup process sounds right. It looks like it can't resolve the plugin in 'app.json'. Did you confirm whether the plugin exists under the directory in which it's searching? I think it should be in node_modules.

Hi, I checked once again and the plugin exists in `node_modules`. Also in development build it never prompt user for permissions.

**Comment by amitferman** [comment]
Did you confirm the path it's looking under is correct (i.e., `/builds/3yoFW7dC/0/<name>/<project_name>`)? Should it be looking under a `builds` dir for the plugin?
