### ISSUE TITLE
Not Working on Expo

### ISSUE THREAD

**Issue by yusufipsum** [amitferman/with-rn-bluetooth-classic#8]
Hi, this library not working on expo. I use expo dev client, not expo go. Permissions and other stuffs OK, i use already a bluetooth library and thats work nicely but i need for advertising process so wanted to try this library. Same error in every method(isBluetoothAvailable, isBluetoothEnabled). Will there be an improvement for this?

tested on real device has API Level 23:
*expo dev client
*react-native version 0.71.8

<img width="864" alt="Ekran Resmi 2023-09-07 17 38 08" src="https://github.com/amitferman/with-rn-bluetooth-classic/assets/35937773/c0ed37a5-6283-4ae6-9c27-48b0d985e129">

app.json:
<img width="769" alt="Ekran Resmi 2023-09-07 17 27 44" src="https://github.com/amitferman/with-rn-bluetooth-classic/assets/35937773/3b6d22bc-aeee-4492-9282-dca46f256dc8">

AndroidManifest.xml:
<img width="864" alt="Ekran Resmi 2023-09-07 17 42 45" src="https://github.com/amitferman/with-rn-bluetooth-classic/assets/35937773/67ea6eaf-896a-40da-9cf0-29ba4d8a108c">

Error: 
<img width="719" alt="Ekran Resmi 2023-09-07 17 46 48" src="https://github.com/amitferman/with-rn-bluetooth-classic/assets/35937773/58b0cacb-cd1c-4707-b68f-a650389876f9">

**Comment by amitferman** [comment]
Thanks for posting the issue. Unfortunately, I am too busy right now to relearn how these permissions work. If you find a fix and post a PR with verification, I'd be happy to approve it.

I would start debugging by looking at whether any of the permissions in this plugin has become unsupported in newer versions.

**Comment by thgh** [comment]
Did you request location & Bluetooth permissions before starting discovery?

**Comment by yusufipsum** [comment]
> Did you request location & Bluetooth permissions before starting discovery?

Yes

**Comment by thgh** [comment]
Here are some snippets of a project that used to work as far as I know
```
    "expo": "~48.0.15",
    "react-native": "0.71.7",
    "react-native-bluetooth-classic": "^1.60.0-rc.26",
    "with-rn-bluetooth-classic": "^1.0.5"

app.json expo.android:
      "permissions": [
        "android.permission.ACCESS_FINE_LOCATION",
        "android.permission.BLUETOOTH_ADMIN",
        "android.permission.BLUETOOTH_ADVERTISE",
        "android.permission.BLUETOOTH_CONNECT",
        "android.permission.BLUETOOTH_SCAN",
        "android.permission.BLUETOOTH"
      ],

      [
        "with-rn-bluetooth-classic",
        {
          "peripheralUsageDescription": "Allow myDevice to check bluetooth peripheral info",
          "alwaysUsageDescription": "Allow myDevice to always use bluetooth info"
        }
      ]


import RNBluetoothClassic from 'react-native-bluetooth-classic'
    RNBluetoothClassic.requestBluetoothEnabled()

import { PermissionsAndroid } from 'react-native'
    const granted = await PermissionsAndroid.requestMultiple([
      PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
      PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
    ])
```

**Comment by thgh** [comment]
@yusuffindik7 note that Bluetooth Classic and Bluetooth Low Energy are unrelated protocols and I'm not aware of devices that support both.

**Comment by yusufipsum** [comment]
> Here are some snippets of a project that used to work as far as I know
> 
> ```
>     "expo": "~48.0.15",
>     "react-native": "0.71.7",
>     "react-native-bluetooth-classic": "^1.60.0-rc.26",
>     "with-rn-bluetooth-classic": "^1.0.5"
> 
> app.json expo.android:
>       "permissions": [
>         "android.permission.ACCESS_FINE_LOCATION",
>         "android.permission.BLUETOOTH_ADMIN",
>         "android.permission.BLUETOOTH_ADVERTISE",
>         "android.permission.BLUETOOTH_CONNECT",
>         "android.permission.BLUETOOTH_SCAN",
>         "android.permission.BLUETOOTH"
>       ],
> 
>       [
>         "with-rn-bluetooth-classic",
>         {
>           "peripheralUsageDescription": "Allow myDevice to check bluetooth peripheral info",
>           "alwaysUsageDescription": "Allow myDevice to always use bluetooth info"
>         }
>       ]
> 
> 
> import RNBluetoothClassic from 'react-native-bluetooth-classic'
>     RNBluetoothClassic.requestBluetoothEnabled()
> 
> import { PermissionsAndroid } from 'react-native'
>     const granted = await PermissionsAndroid.requestMultiple([
>       PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
>       PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
>     ])
> ```

Hi, i was testing on API 23, so Bluetooth Scan and Bluetooth Connect Permissions are not supporting with this device. I don't have Android 12 device. I will find an android 12 device and try again together with scan&connect permissions. If problem is about that, so neccessary API31>= for this library... 

```
const requestPermissions = async () => {
        if(Platform.OS === "android"){
            if((ExpoDevice.platformApiLevel ?? -1) < 31){

                //BLE Library is working fine just this permission
                const granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
                    {
                        title: "Location Permission",
                        message: "Bluetooth requires Location",
                        buttonPositive: "OK",
                    }    
                );
                // const bluetoothScanPermission = await PermissionsAndroid.request(
                //     PermissionsAndroid.PERMISSIONS.BLUETOOTH_SCAN,
                //     {
                //         title: "Scan Permission",
                //         message: "App requires Bluetooth Scanning",
                //         buttonPositive: "OK",
                //     }
                // );
                // const bluetoothConnectPermission = await PermissionsAndroid.request(
                //     PermissionsAndroid.PERMISSIONS.BLUETOOTH_CONNECT,
                //     {
                //         title: "Bluetooth Connect",
                //         message: "App requires Bluetooth Connect",
                //         buttonPositive: "OK",
                //     }
                // );
            return (
                granted === PermissionsAndroid.RESULTS.GRANTED
                // bluetoothScanPermission === PermissionsAndroid.RESULTS.GRANTED &&
                // bluetoothConnectPermission === PermissionsAndroid.RESULTS.GRANTED
                )
            } else {
                const isAndroid31PermissionGranted = 
                    await requestAndroidPermissions();
                return isAndroid31PermissionGranted;
            }
        } else {
            return true;
        }
    };
```

**Comment by yusufipsum** [comment]
OK, it works now. I didn't do anything... just created a new development build and it was fixed...
